### ISSUE TITLE
Not booting from sd card

### ISSUE THREAD

**Issue by frddbbbl** [khumarahn/teres1-gentoo#2]
Hi, I have burned the image to my sd card using the instructions followed, however when booting the laptop it boots straight to ubuntu stored on the computers storage, the sd card is 128gb, is this to big? or is their a way I can manually change the boot device to launch from the sd card

**Comment by khumarahn** [comment]
Hi, this did not happen before. Maybe 128gb is indeed to big (I don't have such a card to test myself)? 

Which exactly image did you get, how exactly did you burn it? Does ubuntu see the sd card?

**Comment by khumarahn** [comment]
Also, if you burn Olimex or any other image, does it boot?

**Comment by frddbbbl** [comment]
Hi, I tried burning it a few different ways, first on my Mac (which doesn't accept oflag and status as operands of dd, I then burnt it using
`dd if=teres-gentoo-20180926.img of=/dev/sdX oflag=direct status=progress`
on the Teres 1, which does recognise the sd card. I will try burning the Olimex image to see it if works, if not I will get a smaller SD card and try again.

**Comment by khumarahn** [comment]
what did you use for /dev/sdX on Teres? If Teres under stock ubuntu does not recognize the sd card, this is a problem.

`oflag=direct` is not very important, its purpose is to avoid large buffers for copying. It is not necessary if you remove the sd card "safely". "status=progress" is also not necessary, only to see the progress. See `man dd`. Basically, you don't need any flags :-)

**Comment by frddbbbl** [comment]
I looked for them with man dd, but they are not on Mac for some reason, I have successfully installed the Olimex image to the sd card and it has launched on the laptop, I burnt it using Etcher that they recommended in the source documentation, so it is not an issue with it recognising the sd card, could it be an issue of the laptop not trying to boot the sd when it has the gentoo image on it?

**Comment by khumarahn** [comment]
Can you try to verify what gets burned on the sd card:
```
dd if=/dev/sdX bs=1048576 count=7565 | sha256sum
```
where `/dev/sdX` is the sdcard, and `7565 * 1048576 =  7932477440` is size of the image file in bytes. This should be ran after burning before you attempt to boot, because booting may change the image.

**Comment by frddbbbl** [comment]
Hi, I've managed to get it working by flashing the file using Etcher, for the first few of my tries I hadn't extracted the img from the .xz ... whoops sorry!

**Comment by khumarahn** [comment]
:-)
