### ISSUE TITLE
Blackscreen on startx

### ISSUE THREAD

**Issue by frddbbbl** [khumarahn/teres1-gentoo#4]
sorry to bother you yet again, but after updating @world and then installing qtwebkit on the next boot of x the screen turns off and I cannot do anything(can't change tty or exit x)
the only thing in my .xinitrc, which is loaded from my bash profile is:
`xbindkeys &
exec dwm`
I cannot find this issue posted about anywhere else so was wondering if it could be specific to Teres? what log files would be helpful for you to see?

**Comment by khumarahn** [comment]
Hi. Did you make any progress? Does lightdm still work?

The usual log files to look at would be `/var/log/messages` and `/var/log/Xorg.*.log`.
